### ISSUE TITLE
Unsat constraints

### ISSUE THREAD

**Issue by ryantaplin** [ukc-co663/dependency-solver-RyanTaplin1705#11]
```
TEST unseen-2
TEST unseen-1
TEST unseen-0
TEST seen-9
E: constraint not satisfied: 0
TEST seen-8
E: bad command +target=1; unsat constraint -target=1 +X2=1 +X17=1 +X7=1 +X19=1
TEST seen-7
E: bad command +Y23=1; unsat constraint -Y23=1 +Y22=1 +Z23=1
TEST seen-6
E: bad command +X1=1; unsat constraint -X1=1 +X2=1 +X3=1 +X4=1
TEST seen-5
cost 10000
TEST seen-4
E: bad command +A=1; unsat constraint -A=1 +B=1 +C=1
TEST seen-3
E: bad command +A=1; unsat constraint -A=1 +B=1 +C=1
TEST seen-2
E: bad command +A=1; unsat constraint -A=1 +C=3
TEST seen-1
E: bad command +mysql-server-5.1=15548; unsat constraint -mysql-server-5.1=15548 +mysql-client-5.1=15548 +mysql-client-5.1=15550
TEST seen-0
cost 9
```

|  Test   | Result | Constraints | Desired |
| ------------- | ------------- | ----- | --- |
| s-0 | cost 9 | ["+A"] | |
| s-1 | E: bad command +mysql-server-5.1=15548; unsat constraint -mysql-server-5.1=15548 +mysql-client-5.1=15548 +mysql-client-5.1=15550 | ["+scala-library=12373", "+scala=12373", "+mysql-server-5.1=15548", "+mysql-client-5.1=15548", "+libplrpc-perl=5915", "+libnet-daemon-perl=4950", "+libmysql-java=15534", "+libdbi-perl=10373", "+libdbd-mysql-perl=15319", "+etherpad=6437"] | |
| s-2 | E: bad command +A=1; unsat constraint -A=1 +C=3 | ["+A"] |  ["+I=9","+G=7","+E=8","+D=0","+C=3","+B=2","+A=1"] |
| s-3 | E: bad command +A=1; unsat constraint -A=1 +B=1 +C=1 | ["+A"] | |

I'm going to stop compiling this table... Something seems off, these files don't even seem to have the constraints in the constraints.json...? @rgrig @julien-lange any advice?

**Comment by rgrig** [comment]
You are installing packages when their dependencies are not yet installed. For example, in seen-3, you issued the command +A=1 and that led to a state in which (A=1 was installed AND C=3 was not installed), but any valid state must have (A=1 not installed OR C=3 installed), according to repository.json.

See also https://piazza.com/class/jclhiyqrax45jw?cid=25 for the notation of the output printed by ./judge.py.

**Comment by ryantaplin** [comment]
Yeah it turns out my recent change to my recursive call to prevent stackoverflow wasn't correct and didn't actually install everything correctly. I think i'm going to have to revert back to the previous version and start that again.

Thanks.

**Comment by ryantaplin** [comment]
@rgrig Are our highest scores recorded and saved? I noticed at one point I had about 3 marks and when I looked back on it later it went down to 0. 

Just trying to work out if I need to have my best solution pushed up onto master branch before the deadline.
