### ISSUE TITLE
no output for seen-0

### ISSUE THREAD

**Issue by rgrig** [ukc-co663/dependency-solver-RyanTaplin1705#4]
With dc09d61c861e1a15ce2c72c538a27224b240264c, I get no output for seen-0.

**Comment by rgrig** [comment]
also on seen-5

**Comment by rgrig** [comment]
also seen-7

**Comment by ryantaplin** [comment]
Was missing the printResults() method call. Now fixed in 784c2b9104bd9d2fa4939613633088654bff822c.
