### ISSUE TITLE
null deref on seen-1

### ISSUE THREAD

**Issue by rgrig** [ukc-co663/dependency-solver-RyanTaplin1705#5]
With dc09d61c861e1a15ce2c72c538a27224b240264c, seen-1 fails with an exception:

> root@66eacdfd3d71:/depsolver/to-test# ./solve ../tests/seen-1/repository.json ../tests/seen-1/initial.json ../tests/seen-1/constraints.json 
> Exception in thread "main" java.lang.NullPointerException
> 	at repository.RepositoryPackages.ofVersions(RepositoryPackages.java:29)
> 	at util.JSONConverter.parseDependants(JSONConverter.java:45)
> 	at util.Setup.readRepository(Setup.java:50)
> 	at Main.main(Main.java:16)
>

**Comment by ryantaplin** [comment]
Now fixed with earlier change to PackageRepository 410ba6b71ee541c42de605706d50591959f05f82. A new issue has occurred; stackOverFlowError. Will update other issue accordingly.
