### ISSUE TITLE
NoSuchElement for seen-2

### ISSUE THREAD

**Issue by rgrig** [ukc-co663/dependency-solver-RyanTaplin1705#6]
Test seen-2 fails with an exception:

> root@66eacdfd3d71:/depsolver/to-test# ./solve ../tests/seen-2/repository.json ../tests/seen-2/initial.json ../tests/seen-2/constraints.json 
> Exception in thread "main" java.util.NoSuchElementException
> 	at java.util.LinkedList.getFirst(LinkedList.java:244)
> 	at model.Machine.optimal(Machine.java:76)
> 	at model.Machine.satisfyConstraints(Machine.java:40)
> 	at Main.start(Main.java:24)
> 	at Main.main(Main.java:20)

**Comment by rgrig** [comment]
also seen-8, also seen-9 as of fix #9

**Comment by ryantaplin** [comment]
# Seen-2 breakdown.
Constraint: ["+A"]
Initial: []

```
+A -> +B and +C 
+B -> +C and +D
+C -> +D and +E
+D -> +E or +F
~+E -> +G and -F (InvalidState package D depends on package F)
+F -> +H
+H -> +J
+J -> none
```
result +J=9, +H=5, +F=4, +D=0, +C=3, +B=2, +A=1

**Comment by ryantaplin** [comment]
Fixed seen-2 and seen-8 in c85c0dae0ad7ed1fac19e1ecfcee6f675135a3f0.

Will start to debug seen-9 now and then work on the stackoverflow issues #7.

**Comment by ryantaplin** [comment]
# Seen-9 Break down
InstallConstraint: ```["+Q01=0","+Q02=0","+Q03=0","+Q04=0","+Q05=0","+Q06=0","+Q07=0","+Q08=0","+Q09=0","+Q10=0","+Q11=0","+Q12=0","+Q13=0","+Q14=0","+Q15=0","+Q16=0","+Q17=0","+Q18=0","+Q19=0","+Q20=0","+Q21=0","+Q22=0","+Q23=0","+Q24=0","+Q25=0","+Q26=0","+Q27=0","+Q28=0","+Q29=0","+Q30=0","+Q31=0","+Q32=0","+Q33=0","+Q34=0","+Q35=0","+Q36=0","+Q37=0","+Q38=0","+Q39=0","+Q40=0"]```
ForbiddenConstraint: 
```["-P01=0","-P02=0","-P03=0","-P04=0","-P05=0","-P06=0","-P07=0","-P08=0","-P09=0","-P10=0","-P11=0","-P12=0","-P13=0","-P14=0","-P15=0","-P16=0","-P17=0","-P18=0","-P19=0","-P20=0","-P21=0","-P22=0","-P23=0","-P24=0","-P25=0","-P26=0","-P27=0","-P28=0","-P29=0","-P30=0","-P31=0","-P32=0","-P33=0","-P34=0","-P35=0","-P36=0","-P37=0","-P38=0","-P39=0","-P40=0"]```

Initial: 
```
["P01=0","P02=0","P03=0","P04=0","P05=0","P06=0","P07=0","P08=0","P09=0","P10=0","P11=0","P12=0","P13=0","P14=0","P15=0","P16=0","P17=0","P18=0","P19=0","P20=0","P21=0","P22=0","P23=0","P24=0","P25=0","P26=0","P27=0","P28=0","P29=0","P30=0","P31=0","P32=0","P33=0","P34=0","P35=0","P36=0","P37=0","P38=0","P39=0","P40=0"]
```

So I will need to remove everything from initial state and apply new things.

# Processing
processConstraints(installConstraints)
```
Q01=0 -> none
Q02=0 -> none
Q03=0 -> none
Q04=0 -> none
Q05=0 -> none
....
Q40=0 -> none
```
will return 1 ValidState (i think) then run .inspector(forbiddenconstraints); uninstall all of the P packages and return that 1 valid state. Ok need to debug to see what processConstraints actually returns. Maybe I should add a pre-processing - remove all forbidden constraints in initial state.

**Comment by ryantaplin** [comment]
Fixed this I think, for seen-9. Now got stackoverflow error for test 9.

I will close this for now and reopen if it retains these issues in the future.
