### ISSUE TITLE
parse (?) exception in seen-4

### ISSUE THREAD

**Issue by rgrig** [ukc-co663/dependency-solver-RyanTaplin1705#8]
Test seen-4 fails with an exception:

> root@66eacdfd3d71:/depsolver/to-test# ./solve ../tests/seen-4/repository.json ../tests/seen-4/initial.json ../tests/seen-4/constraints.json                
> Exception in thread "main" java.lang.Exception: No packages {D} of version < 4.3.5
> 	at repository.RepositoryPackages.ofVersions(RepositoryPackages.java:34)
> 	at util.JSONConverter.parseConflicts(JSONConverter.java:31)
> 	at util.Setup.readRepository(Setup.java:51)
> 	at Main.main(Main.java:16)

 There is an explicit `if` at https://github.com/ukc-co663/dependency-solver-RyanTaplin1705/blob/master/src/repository/RepositoryPackages.java#L34. Why is that an exception? Should it not just return the empty list?

**Comment by ryantaplin** [comment]
I wasn't sure what to do with this use case but based on what you told me earlier I will remove this exception and just return the empty list. It has fixed seen-4 now and is passing. 👍
