### ISSUE TITLE
parse exception on seen-6

### ISSUE THREAD

**Issue by rgrig** [ukc-co663/dependency-solver-RyanTaplin1705#9]
Test seen-6 fails with an exception:

> root@66eacdfd3d71:/depsolver/to-test# ./solve ../tests/seen-6/repository.json ../tests/seen-6/initial.json ../tests/seen-6/constraints.json
> Exception in thread "main" java.lang.NumberFormatException: For input string: "=1"
> 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> 	at java.lang.Integer.parseInt(Integer.java:580)
> 	at java.lang.Integer.parseInt(Integer.java:615)
> 	at util.VersionChecker.versionEvaluate(VersionChecker.java:18)
> 	at repository.RepositoryPackages.ofVersions(RepositoryPackages.java:30)
> 	at util.Setup.readConstraints(Setup.java:78)
> 	at Main.main(Main.java:18)
>

**Comment by rgrig** [comment]
also seen-9

**Comment by ryantaplin** [comment]
Parse issue fixed; new issue occurred, will raise new issue or move into existing issue for 'StackOverflow'.
